# Generated by Django 5.2.18 on 2026-10-06 17:51

import apps.common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('to_email', models.EmailField(max_length=254)),
                ('template_key', models.CharField(blank=True, max_length=64)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='queued', max_length=32)),
                ('provider_id', models.CharField(blank=True, max_length=128)),
                ('error', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('scope_type', models.CharField(choices=[('global', 'Global'), ('program', 'Program'), ('cohort', 'Cohort'), ('class', 'Class'), ('subject', 'Subject'), ('user', 'User')], default='class', max_length=32)),
                ('scope_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('body_json', models.JSONField(blank=True, default=dict)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=True)),
                ('send_email', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pinned', '-publish_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('email_announcements', models.BooleanField(default=True)),
                ('email_grades', models.BooleanField(default=True)),
                ('email_payments', models.BooleanField(default=True)),
                ('email_digest', models.BooleanField(default=False)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
