# Generated by Django 5.2.18 on 2026-10-06 17:39

import apps.common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        ('courses', '0004_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('timestamp_s', models.PositiveIntegerField(blank=True, null=True)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='courses.subtopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('upvote_count', models.PositiveIntegerField(default=0)),
                ('is_resolved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_questions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.subject')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='courses.subtopic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('is_instructor', models.BooleanField(default=False)),
                ('upvote_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='learning.question')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('available', 'Available'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='available', max_length=16)),
                ('percent', models.PositiveSmallIntegerField(default=0)),
                ('time_spent_s', models.PositiveIntegerField(default=0)),
                ('first_opened_at', models.DateTimeField(blank=True, null=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_progress', to='admissions.enrollment')),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_rows', to='courses.subtopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'subtopic'), name='uniq_item_progress_user_subtopic')],
            },
        ),
        migrations.CreateModel(
            name='SubjectProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('percent', models.PositiveSmallIntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_progress', to='admissions.enrollment')),
                ('last_subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.subtopic')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_rows', to='courses.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'subject'), name='uniq_subject_progress_user_subject')],
            },
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('last_position_s', models.PositiveIntegerField(default=0)),
                ('furthest_position_s', models.PositiveIntegerField(default=0)),
                ('watched_segments', models.JSONField(blank=True, default=list)),
                ('watched_pct', models.PositiveSmallIntegerField(default=0)),
                ('playback_rate', models.FloatField(default=1.0)),
                ('caption_lang', models.CharField(blank=True, max_length=16)),
                ('device_id', models.CharField(blank=True, max_length=64)),
                ('client_ts', models.BigIntegerField(default=0)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to='courses.subtopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL)),
                ('video_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_rows', to='courses.videoasset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'subtopic'), name='uniq_video_progress_user_subtopic')],
            },
        ),
    ]
