# Generated by Django 5.2.18 on 2026-10-06 13:34

import apps.common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.JSONField(blank=True, default=dict)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cohorts/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('timezone', models.CharField(default='Africa/Lagos', max_length=64)),
                ('capacity', models.PositiveIntegerField(default=50)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('applications_open', 'Applications open'), ('applications_closed', 'Applications closed'), ('running', 'Running'), ('completed', 'Completed'), ('archived', 'Archived')], default='planned', max_length=32)),
                ('application_opens_at', models.DateTimeField(blank=True, null=True)),
                ('application_closes_at', models.DateTimeField(blank=True, null=True)),
                ('application_fee_kobo', models.BigIntegerField(blank=True, help_text='Override application fee in kobo; null = inherit global default', null=True)),
                ('waitlist_enabled', models.BooleanField(default=False)),
                ('waitlist_auto_promote', models.BooleanField(default=False)),
                ('acceptance_deadline_days', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('description_rich', models.JSONField(blank=True, default=dict)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='programs/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('default_currency', models.CharField(default='NGN', max_length=3)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='classes/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('capacity', models.PositiveIntegerField(default=50)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='programs.cohort')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='cohort',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohorts', to='programs.program'),
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('mode', models.CharField(choices=[('linked', 'Linked'), ('cloned', 'Cloned')], default='linked', max_length=16)),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='programs.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_links', to='courses.subject')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('class_ref', 'subject'), name='uniq_class_subject')],
            },
        ),
        migrations.CreateModel(
            name='ClassTutor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('lead', 'Lead'), ('assistant', 'Assistant')], default='lead', max_length=16)),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to='programs.class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_tutors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('class_ref', 'user'), name='uniq_class_tutor')],
            },
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('cohort', 'slug'), name='uniq_class_slug_per_cohort'),
        ),
    ]
