# Generated by Django 5.2.18 on 2026-10-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
