# Generated by Django 5.2.18 on 2026-10-06 13:23

import apps.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('org_name', models.CharField(default='Imo Ijinle Academy', max_length=128)),
                ('logo_url', models.URLField(blank=True)),
                ('favicon_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#1F5C4D', max_length=16)),
                ('accent_color', models.CharField(default='#C8943A', max_length=16)),
                ('background_color', models.CharField(default='#FBFAF7', max_length=16)),
                ('foreground_color', models.CharField(default='#16201C', max_length=16)),
                ('ink_color', models.CharField(default='#14201C', max_length=16)),
                ('ink2_color', models.CharField(default='#1E2C27', max_length=16)),
                ('ink_foreground', models.CharField(default='#F4F2EC', max_length=16)),
                ('font_display', models.CharField(default='Fraunces', max_length=64)),
                ('font_ui', models.CharField(default='Inter', max_length=64)),
                ('extra_css_vars', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'Brand settings',
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('base_url', models.URLField(default='http://localhost:3000')),
                ('support_email', models.EmailField(default='support@imoijinle.local', max_length=254)),
                ('default_timezone', models.CharField(default='Africa/Lagos', max_length=64)),
                ('default_locale', models.CharField(default='en', max_length=16)),
                ('application_grace_for_closed_cohorts', models.BooleanField(default=True)),
                ('require_fee_before_admit', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
