# Generated by Django 5.2.18 on 2026-10-06 13:34

import apps.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgsettings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFeeSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('default_amount_kobo', models.BigIntegerField(default=500000)),
                ('is_free', models.BooleanField(default=False)),
                ('refundable_policy', models.JSONField(blank=True, default=dict)),
                ('fee_required_before_admit', models.BooleanField(default=True)),
                ('waiver_codes', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name_plural': 'Application fee settings',
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewaySettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], default='test', max_length=8)),
                ('public_key', models.CharField(blank=True, max_length=255)),
                ('secret_key_encrypted', models.TextField(blank=True)),
                ('default_currency', models.CharField(default='NGN', max_length=3)),
                ('channel_card', models.BooleanField(default=True)),
                ('channel_bank', models.BooleanField(default=True)),
                ('channel_ussd', models.BooleanField(default=True)),
                ('channel_transfer', models.BooleanField(default=True)),
                ('channel_mobile_money', models.BooleanField(default=False)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_ok', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Payment gateway settings',
            },
        ),
    ]
