# Generated by Django 5.2.18 on 2026-10-06 13:34

import apps.common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=240)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description_json', models.JSONField(blank=True, default=dict)),
                ('language', models.CharField(default='en', max_length=16)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all', 'All levels')], default='all', max_length=16)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('subcategory', models.CharField(blank=True, max_length=64)),
                ('primary_topic_tags', models.JSONField(blank=True, default=list)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='subjects/')),
                ('promo_video', models.URLField(blank=True)),
                ('intended_learners', models.JSONField(blank=True, default=dict, help_text='{"learn": [], "requirements": [], "audience": []}')),
                ('welcome_message', models.TextField(blank=True)),
                ('completion_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('instructors', models.ManyToManyField(blank=True, related_name='subjects_instructing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('objective_text', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.subject')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('subtopic', 'Subtopic (lesson)'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('practice_test', 'Practice test')], default='subtopic', max_length=32)),
                ('is_published', models.BooleanField(default=False)),
                ('is_free_preview', models.BooleanField(default=False)),
                ('estimated_time_s', models.PositiveIntegerField(default=0)),
                ('min_time_s', models.PositiveIntegerField(default=0)),
                ('description_json', models.JSONField(blank=True, default=dict)),
                ('drip_rule', models.JSONField(blank=True, default=dict)),
                ('unlock_rule', models.JSONField(blank=True, default=dict)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='courses.topic')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
