# Generated by Django 5.2.18 on 2026-10-06 17:25

import apps.common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_subject_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='mock', max_length=32)),
                ('provider_asset_id', models.CharField(blank=True, max_length=128)),
                ('playback_id', models.CharField(blank=True, max_length=128)),
                ('policy', models.CharField(default='signed', max_length=16)),
                ('duration_s', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('errored', 'Errored'), ('converted', 'Converted')], default='ready', max_length=16)),
                ('captions', models.JSONField(blank=True, default=list)),
                ('chapters', models.JSONField(blank=True, default=list)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('downloadable', models.BooleanField(default=False)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='pricing',
            field=models.JSONField(blank=True, default=dict, help_text='{"mode":"free|class_fee|paid","amount_kobo":0,"currency":"NGN"}'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='require_full_watch',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SubjectPreviewToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_tokens', to='courses.subject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubtopicResource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('file', 'Downloadable file'), ('link', 'External link'), ('library', 'Library asset')], default='file', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('download_allowed', models.BooleanField(default=True)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.subtopic')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('content', 'Subtopic content'), ('resource', 'Resource'), ('cover', 'Cover image'), ('caption', 'Caption'), ('promo', 'Promo video')], max_length=32)),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('errored', 'Errored'), ('converted', 'Converted')], default='uploading', max_length=16)),
                ('object_key', models.CharField(blank=True, max_length=512)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='courses.subtopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubtopicContent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('video_slides', 'Video + slides'), ('article', 'Article'), ('pdf', 'PDF'), ('spreadsheet', 'Spreadsheet'), ('document', 'Document (Word)'), ('presentation', 'Presentation'), ('audio', 'Audio'), ('image', 'Image'), ('link', 'Link / Embed'), ('live', 'Live session')], max_length=32)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body_json', models.JSONField(blank=True, default=dict)),
                ('file', models.FileField(blank=True, null=True, upload_to='content/')),
                ('preview_file', models.FileField(blank=True, null=True, upload_to='content/preview/')),
                ('external_url', models.URLField(blank=True)),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('processing_status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('errored', 'Errored'), ('converted', 'Converted')], default='ready', max_length=16)),
                ('duration_s', models.PositiveIntegerField(default=0)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('subtopic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='courses.subtopic')),
                ('video_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='courses.videoasset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
