# Generated by Django 5.2.18 on 2026-10-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_m3_authoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoasset',
            name='provider',
            field=models.CharField(default='mux', max_length=32),
        ),
    ]
