# Generated by Django 5.2.18 on 2026-10-06 17:51

import apps.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OIDCSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('issuer', models.URLField(blank=True)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('client_secret_encrypted', models.TextField(blank=True)),
                ('scopes', models.CharField(default='openid profile email', max_length=255)),
                ('redirect_path', models.CharField(default='/auth/oidc/callback', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'OIDC settings',
            },
        ),
    ]
