# Generated by Django 5.2.18 on 2026-10-06 14:11

import apps.common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaystackWebhookEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('event_type', models.CharField(blank=True, max_length=64)),
                ('signature_valid', models.BooleanField(default=False)),
                ('payload_hash', models.CharField(max_length=64, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('application', 'Application fee'), ('class', 'Class fee'), ('custom', 'Custom')], max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('void', 'Void')], default='open', max_length=32)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('amount_minor', models.BigIntegerField()),
                ('amount_paid_minor', models.BigIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('provider', models.CharField(default='paystack', max_length=32)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='initiated', max_length=32)),
                ('channel', models.CharField(blank=True, max_length=32)),
                ('access_code', models.CharField(blank=True, max_length=128)),
                ('authorization_url', models.URLField(blank=True)),
                ('paystack_id', models.CharField(blank=True, max_length=64)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('fees_minor', models.BigIntegerField(default=0)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=128)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
